language: elixir
elixir:
  - 1.6
otp_release:
  - 20.0
sudo: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -qq gcc-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo apt-get install -qq portaudio19-dev
